### ISSUE TITLE
No load_data function in the utils.py file

### ISSUE THREAD

**Issue by SaqibMamoon** [m4urin/temporal-causal-discovery#4]
@m4urin  Thank you sharing the code online, however, I can't find the load function in the utils.py file. could you please have a look.

thanks a lot.

**Comment by m4urin** [comment]
Hi @SaqibMamoon, thanks for showing interest in this project! However, know that this is still research in progress, and I've refactored the code multiple times for new experiments, which resulted in quite a messy code base. I will be fixing it this month as I am finishing up my thesis.
For now, the load data function is located at https://github.com/m4urin/temporal-causal-discovery/blob/main/src/data/dataset.py and is also able to import DREAM3.


```
from src.data import load_dataset

causeme_data = load_dataset('causeme', 'nonlinear-VAR_N-10_T-300')
dream3_data = load_dataset('dream3', 'ecoli1')
```
